---
title: "BIOS735 Group 6 Final project"
author: "Group 6"
date: "4/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pkgs <- list('tidyverse', 'table1', 'e1071', 'caret', 'ROCR')
lapply(pkgs, require, character.only = T)
```

## Data pre-processing

We'll use bank-full.csv and randomly select 20% data as our full working dataset.

```{r}
## read data
dat_full <- read_delim("bank-full.csv",
           delim=';')

## overview
table1(~.|y, data = dat_full)

#check null
sum(is.na(dat_full)) #0
summary(dat_full)

dat_full %>% group_by(education) %>% summarize(count=n())


## combine the labels
library(car)

unknown <- c('unknown')
no_income <- c('unemployed','student')
low_income <- c('blue-collar','housemaid','retired','self-employed')
high_income <- c('admin.','entrepreneur','management','services','technician')



spring <- c('mar','feb','jan')
summer <- c('apr','may','jun')
autumn <- c('jul','aug','sep')
winter <- c('nov','oct','dec')



dat_full$job<-recode(dat_full$job,"unknown='unknown'; no_income='no_income';
                      low_income = 'low_income'; high_income = 'high_income'")

dat_full$month<-recode(dat_full$month,"spring='1_2_3'; summer='4_5_6';
                      autumn = '7_8_9'; winter = '10_11_12'")

# select variables (data pre-processing: keep consistent)
#drop pdays
dat = dat_full %>% select(-pdays)

scale2sd <- function(x) {
  (x - mean(x) )/ (2*sd(x))
}


```

```{r}
dat.working <- dat %>% 
  mutate(age = scale2sd(age),
         campaign = scale2sd(campaign),
         balance = scale2sd(balance),
         duration = scale2sd(duration),
         previous = scale2sd(previous)) %>% # put continuous vars on same scale as indicators
  mutate_if(is.character, as.factor)%>% 
  slice_sample(prop = 0.2)# convert character to factor

summary(dat.working)

# # check data imbalance
# dat.working %>% group_by(y) %>% summarize(count=n())


# #downsampling
# set.seed(100)
# dat.downsampled <- downSample(x=dat.working[,-ncol(dat.working)], y=dat.working$y)

# select training and testing data
set.seed(100)
y <- dat.working$y
index <- createDataPartition(
  y,
  times = 1,
  p = 0.8,
  list = F,
  groups = min(5, length(y))
)
dat_train <- dat.working[index,]
dat_test <- dat.working[-index,]

```

visualizations
```{r}
library(ggplot2)
ggplot(dat_full, aes(x = y, y = age)) + xlab('subscribed')+
  geom_boxplot(color = "steelblue")

ggplot(dat_full, aes(x = y, y = balance)) + xlab('subscribed')+
  geom_boxplot(color = "steelblue")+ theme_classic()+ ggtitle('boxplot based on labels')

ggplot(dat_full, aes(x = age, fill = y)) + geom_density(alpha = 0.5,position = 'stack') + theme_classic()+ labs(fill = "subscribed") + ggtitle('age density plot based on labels')

```

```{r}
summary(dat_full$age)
```


```{r}
#visualization
library(corrplot)
new <- dat_full[,c(1,6,10,12,13,14,15)]
res <- cor(new)
corrplot(res,type = "upper", order = "hclust", 
        tl.col = "black", tl.srt = 45)

```

```{r}
library(dplyr) # for select and case_when and group_by
data_new = dat_full%>%
  select(age, balance)%>%
  mutate(age_group =  case_when(age < 20 ~ "<20",
                                
                           30 > age & age >= 20 ~ "20-30",
                           40> age & age >= 30 ~ "30-40",
                         50 > age & age >= 40 ~ "40-50",
                           60 > age & age >= 50 ~ "50-60",
                         70 > age & age >= 60 ~ "60-70",
                         80 > age & age >=70 ~ "70-80",
                         age >= 80 ~ "80-100"
                         
                         ))%>%
  group_by(age_group)%>%
  summarise(mean_balance = sum(balance)/n() )
```

```{r}
ggplot(data_new, aes( y=mean_balance, x=age_group)) + 
    geom_bar(position="dodge", stat="identity",fill = 'plum3') +
  ggtitle('mean_balance by age group') + theme_minimal()

```

```{r}
# Grouped
# library(RColorBrewer)
# coul <- brewer.pal(2, "Set2") 
ggplot(dat_full, aes(fill=y, y= campaign, x=job)) + 
    geom_bar(position="stack", stat="identity") + theme_classic()+ labs(fill = "subscribed") + ggtitle('Number of total campaigns sent for each job_type')+scale_fill_manual(values = c("burlywood1","darkolivegreen3"))
```



